### ISSUE TITLE
Protocols as programs and security properties

### ISSUE THREAD

**Issue by WizardOfAus** [awslabs/quivela#1]
Hey Daniel!

Looks like an interesting talk but cannot attend. Just curious where I could read up more on the protocols and security properties that AWS uses to protect customers' data? And find out more about Quivela's tools

**Comment by seanmcl** [comment]
Hi @WizardOfAus.  

Thanks for the question!  Quivela is a new project we're experimenting with.  Some projects we've done in the past related to your question are here: https://aws.amazon.com/security/provable-security/

More general security info at AWS can be found here: https://aws.amazon.com/security/

Best,

Sean
