### ISSUE TITLE
envelope and envelope-small test suites are currently broken

### ISSUE THREAD

**Issue by rcook** [awslabs/quivela#9]
Repro steps:

1. Open terminal in project directory
2. Build with `stack build`
3. Run tests with `stack test quivela:envelope` and `stack test quivela:envelope-small`

Both test suites return 1. I haven't had a chance to dig any deeper yet.

The same two suites are causing the Travis-CI build to fail: https://travis-ci.org/awslabs/quivela/builds/479090112

**Comment by seanmcl** [comment]
Yes, there was a bad hack we removed recently that allowed them to pass.  (The Haskell code added assertions based on identifiers just in the envelope tests.)  I'm working on re-enabling them by allowing propositions in the concrete syntax.  Should be fixed by end of week.

**Comment by seanmcl** [comment]
I disabled the tests for now.  This is a known issue.
